### ISSUE TITLE
Sample usage in README doesn't compile

### ISSUE THREAD

**Issue by bonsairobo** [SSPkrolik/nimxplot#1]
`flip_coins.nim(16, 20) Error: type mismatch: got (Rect, seq[tuple[x: float64, y: float64]])
but expected one of: 
plotxy.newPlotXY(r: Rect, model: ModelXYColor[system.float64])`

**Comment by robfinner** [comment]
i have same error on windows 7

**Comment by robfinner** [comment]
I added a PR to fix this. Change the example call to: 

var gxy = newPlotXY(
  newRect(0, 0, 1024, 768),
  @[(x: 0.0, y: 0.0, color: blackColor()), (x: 10.0, y: 10.0, color: blackColor()), (x: 20.0, y: 10.0, color: blackColor()),
    (x: 60.0, y: 300.0, color: blackColor()), (x: 100.0, y: 200.0, color: blackColor())]
)

**Comment by SSPkrolik** [comment]
Thx!
